services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=catalogdb;Database=CatalogDb;User Id=sa;Password=Password123;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - catalogdb


  catalogdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=orderingdb;Database=OrderingDb;User Id=sa;Password=Password123;TrustServerCertificate=True;
    ports:
      - "5001:8080"
    depends_on:
      - orderingdb


  orderingdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1434:1433"

