services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile


  catalogdb:
    image: mcr.microsoft.com/mssql/server
  
  
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering.API/Dockerfile

  orderingdb:
    image: mcr.microsoft.com/mssql/server

