services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=catalogdb;Database=CatalogDb;User Id=sa;Password=Password123;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - catalogdb


  catalogdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1433:1433"
#    volumes:
#      - catalogdb_data:/var/opt/mssql

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=orderingdb;Database=OrderingDb;User Id=sa;Password=Password123;TrustServerCertificate=True;
    ports:
      - "5002:8080"
    depends_on:
      - orderingdb


  orderingdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
    ports:
      - "1434:1433"
#    volumes:
#      - orderingdb_data:/var/opt/mssql


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Redis=basketdb:6379
    ports:
      - "50001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basketdb:
    restart: always
    ports:
      - "6379:6379"
 

  web.bff.shopping:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "10000:8080"

