services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile


  catalogdb:
    image: mcr.microsoft.com/mssql/server
  
  
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Ordering.API/Dockerfile

  orderingdb:
    image: mcr.microsoft.com/mssql/server


  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket.API/Dockerfile
    depends_on:
      - basketdb  
      
      
  basketdb:    
    image: redis
     
      
#volumes:
#  catalogdb_data:
#  orderingdb_data:      

